apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-bnljwfxj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-bnljwfxj 
  name: go-bnljwfxj
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-bnljwfxj
    weight: 100 
